[tools]
bat = "latest"
bat-extras = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
jqp = "latest"
lazygit = "latest"
"aqua:neovim/neovim" = "latest"
ripgrep = "latest"
starship = "latest"
xh = "latest"
yq = "latest"

[settings]
experimental = true
lockfile = true
