[tools]
bat = "latest"
bat-extras = "latest"
delta = "0.18"
eza = "latest"
fd = "10.3.0"
fzf = "latest"
jqp = "latest"
lazygit = "latest"
node = "22"
"aqua:neovim/neovim" = "latest"
ripgrep = "latest"
starship = "latest"
xh = "latest"
yq = "latest"

[settings]
experimental = true
lockfile = true

[settings.python]
compile = true
